#!/bin/bash
git rev-parse HEAD | awk ' BEGIN {print "#include \"version.h\"\r\n\r\n//File generated by automatically. Any manual change will be rewritten\r\n"} {print "const char * build_git_sha = \"" $0"\";\r\n"} END {}' > ./version.c
git log -1 | grep Author | awk 'BEGIN {} {print "const char * build_git_author= \""$0"\";\r\n"} END {} ' >> ./version.c

