#include "version.h"

//File generated by automatically. Any manual change will be rewritten
const char * build_git_sha = "3d756927add8a6b465f3ce53c2286802de05ef9f";
const char * build_git_author= "Author: elmagnifico <elmagnificogg@gmail.com>";
